name: Slack Notifications

env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    SLACK_CHANNEL: C028FDNKE1H

on:
  push:
    branches:
      - master

jobs:
  success-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: exit 0
      - name: Slack Success
        if: success()
        uses: abinoda/slack-action@master
        with:
          args: >-
            {
              "channel": "C028FDNKE1H",
              "attachments": [
                {
                  "mrkdwn_in": ["text"],
                  "color": "#36a64f",
                  "pretext": "Built branch ${{ github.ref }}",
                  "author_name": "${{ github.actor }}",
                  "author_link": "http://flickr.com/bobby/",
                  "author_icon": "https://placeimg.com/16/16/people",
                  "title": "${{ github.workflow }}",
                  "title_link": "https://api.slack.com/",
                  "text": "Optional `text` that appears within the attachment",
                  "thumb_url": "http://placekitten.com/g/200/200",
                  "footer": "Github Actions",
                  "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                  "ts": 123456789
                }
              ]
            }

