name: Slack Notifications

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

on:
  workflow_run:
    workflows: [Master, CI]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Display workflow_run context
        uses: actions/github-script@v6
        with:
          script: console.log(JSON.stringify(context, null, 2))
      - name: Build Failed! Send message to Slack API
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_BOT_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "!!! BUILD FAILED !!!\nRepository: ${{ github.event.repository.full_name }}\nBranch: ${{ github.event.workflow_run.head_branch }}\nLatest Commiter: ${{ github.event.workflow_run.head_commit.author.name }}\nLastest Commit: ${{ github.event.workflow_run.head_repository.html_url }}/commit/${{ github.event.workflow_run.head_sha }}\nWorkflow: ${{ github.event.workflow_run.html_url }}"
                  }
                }
              ]
            }
