name: Notify Slack

env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    SLACK_CHANNEL: C028FDNKE1H

on:
  workflow_dispatch:

steps:
  uses: pullreminders/slack-action@master
  with:
    args: '{\"channel\":\"C028FDNKE1H\",\"text\":\"Hello world\"}'
