name: Slack Notifications

env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    SLACK_CHANNEL: C028FDNKE1H

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  notifySlack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@master
        with:
          args: <-
            {
              "channel": "C028FDNKE1H",
              "text": "Still works"
            }
