name: Slack Notifications

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

on:
  workflow_run:
    workflows: [Master, CI]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Display workflow_run context
        uses: actions/github-script@v6
        with:
          script: console.log(JSON.stringify(context, null, 2))
      - name: Build Failed! Send message to Slack API
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_BOT_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.workflow_run.html_url }}|Build Failed!>"
                    "emoji": true
                  }
                },
            	{
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.event.repository.full_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.event.workflow_run.head_branch }}"
                    }
                  ]
                },
            	{
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Latest Commiter:*\n${{ github.event.workflow_run.head_commit.author.name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit Message:*\n<${{ github.event.workflow_run.head_repository.html_url }}/commit/${{ github.event.workflow_run.head_sha }}|${{ github.event.workflow_run.head_commit.message }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.workflow_run.html_url }}|Failed Workflow>"
                  }
                }
              ]
            }
