# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    SLACK_CHANNEL: C028FDNKE1H

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use Yarn 2.x PnP
      run: yarn set version berry 

    - name: Install Dependencies
      run: yarn


  build:
    needs: setup
    strategy:
      matrix:
        node-version: [15.x, 16.x]
    runs-on: ubuntu-latest
    steps:
    - name: Build Intermediates
      run: yarn build

  test:
    needs: build
    strategy:
      matrix:
        node-version: [15.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Suite
        run: yarn test

  notify:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Slack Success
        if: success()
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"C028FDNKE1H\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* ${{ github.event.pull_request.title }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Who?:* ${{ github.event.pull_request.user.login }}\n*Request State:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ github.event.pull_request.html_url }}|View Pull Request>\"}}]}'

